name: playwith_customer_app
description: ""

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # MIDI
  # flutter_midi_pro: ^2.0.0
  flutter_midi_pro: ^3.1.3
  flutter_midi_command: ^0.4.16
  dart_midi_pro:
    git:
      url: https://github.com/Fluttely/dart_midi_pro.git
      ref: 94073f3d03c319156b940047d2e92bbbd19c75b6
  piano: ^1.0.4
  flutter_piano_pro: ^0.6.0

  file_picker: ^8.0.5
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  time: ^2.1.4

dependency_overrides:
  analyzer: ^5.0.0

dev_dependencies:
  build_runner: ^2.1.10
  dart_code_metrics: ^4.15.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  mocktail: ^0.3.0
  test: ^1.22.0

flutter:
  uses-material-design: true

  assets:
    - assets/soundfonts/
    - assets/soundfonts/UprightPianoKW-small-20190703.sf2
    - assets/soundfonts/YDP-GrandPiano-20160804.sf2
    - assets/midi/
    - assets/midi/test.mid
    - assets/midi/mario.mid
    - assets/midi/untitled.mid
    - assets/midi/super_mario_64_medley.mid
    
# flutter pub run build_runner build --delete-conflicting-outputs